title: "Marta Castiñeira Reis"
author: "Marta Castiñeira Reis"

navbar-links:
  About: "/"
  Research: "research"
  Outputs:
    Publications: "publications"
    Software & Data: "software"
  Teaching: "teaching"
  Talks: "talks"
  CV: "cv"

avatar: "/assets/img/marta.jpg"
round-avatar: true

social-network-links:
  email: "TU_CORREO_PUBLICO"
  github: "TU_USUARIO"
  linkedin: "marta-castiñeira-reis-18a31756"
  ORCID: "0000-0003-4204-3474"
  google-scholar: "TU_ID_DE_GOOGLE_SCHOLAR"

post_search: false
edit_page_button: false
